// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYAbWAMcXfaS80qtsv3I92-AoMIDE3wgE',
    appId: '1:103930259460:web:78c994a7be1cfec7896d51',
    messagingSenderId: '103930259460',
    projectId: 'to-do-app-1c2a2',
    authDomain: 'to-do-app-1c2a2.firebaseapp.com',
    storageBucket: 'to-do-app-1c2a2.appspot.com',
    measurementId: 'G-6XQYQV3S5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbN6b38PJxoCVvAl2V6vAuFaiRXM74Aic',
    appId: '1:103930259460:android:da3b30345b3a4b21896d51',
    messagingSenderId: '103930259460',
    projectId: 'to-do-app-1c2a2',
    storageBucket: 'to-do-app-1c2a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKf_x2edGyeoKtoA4rL4EBcDc4zPK0PPs',
    appId: '1:103930259460:ios:4902ae847ad8ae25896d51',
    messagingSenderId: '103930259460',
    projectId: 'to-do-app-1c2a2',
    storageBucket: 'to-do-app-1c2a2.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKf_x2edGyeoKtoA4rL4EBcDc4zPK0PPs',
    appId: '1:103930259460:ios:f6271be97824b261896d51',
    messagingSenderId: '103930259460',
    projectId: 'to-do-app-1c2a2',
    storageBucket: 'to-do-app-1c2a2.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
